// <auto-generated />
using System;
using McSystems.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McSystems.DataAccess.Migrations
{
    [DbContext(typeof(McSystemsContext))]
    [Migration("20221225092736_AllMigrations")]
    partial class AllMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CustomerReservation", b =>
                {
                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationsId")
                        .HasColumnType("int");

                    b.HasKey("CustomersId", "ReservationsId");

                    b.HasIndex("ReservationsId");

                    b.ToTable("CustomerReservation");
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar (100)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = 2,
                            Name = "İngiltere"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fransa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hollanda"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arjantin"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Amerika"
                        });
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAdress")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DateOfBirth")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("HireDate")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<byte>("Floor")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint");

                    b.Property<bool>("InMaintanance")
                        .HasColumnType("bit");

                    b.Property<byte>("Number")
                        .HasMaxLength(10)
                        .HasColumnType("tinyint");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number", "Floor")
                        .IsUnique();

                    b.ToTable("Room", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Floor = (byte)1,
                            InMaintanance = false,
                            Number = (byte)1,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Floor = (byte)1,
                            InMaintanance = false,
                            Number = (byte)2,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            Floor = (byte)1,
                            InMaintanance = false,
                            Number = (byte)3,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            Floor = (byte)1,
                            InMaintanance = false,
                            Number = (byte)4,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 2,
                            Floor = (byte)2,
                            InMaintanance = false,
                            Number = (byte)1,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 2,
                            Floor = (byte)2,
                            InMaintanance = false,
                            Number = (byte)2,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 4,
                            Floor = (byte)2,
                            InMaintanance = false,
                            Number = (byte)3,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 4,
                            Floor = (byte)2,
                            InMaintanance = false,
                            Number = (byte)4,
                            RoomType = 1
                        });
                });

            modelBuilder.Entity("CustomerReservation", b =>
                {
                    b.HasOne("McSystems.DataAccess.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McSystems.DataAccess.Entities.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Customer", b =>
                {
                    b.HasOne("McSystems.DataAccess.Entities.Country", "Country")
                        .WithMany("Customers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Reservation", b =>
                {
                    b.HasOne("McSystems.DataAccess.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Country", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
